run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - errname
    - gci
    - gofumpt
    - gosec
    - stylecheck
    - unconvert
    - unparam

issues:
  fix: true
